# Generated by Django 3.2.4 on 2021-06-30 04:25

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_managerlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='Slider1',
            field=models.ImageField(default='static/default.jpg', upload_to='static/slider_image/', validators=[task.models.validate_slider_image]),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='Slider2',
            field=models.ImageField(default='static/default.jpg', upload_to='static/slider_image/', validators=[task.models.validate_slider_image]),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='Slider3',
            field=models.ImageField(default='static/default.jpg', upload_to='static/slider_image/', validators=[task.models.validate_slider_image]),
        ),
    ]
